Repository ros/ros, pull requests merged in 2020-04, with the labels that each got.

#251 Fix log purge on Windows
  tools/rosclean/src/rosclean/__init__.py
Labels: bug, consider-backport

#247 Implemented move functionality to move a file from package to target
  tools/rosbash/rosbash
  tools/rosbash/rosfish
  tools/rosbash/rostcsh
  tools/rosbash/roszsh
Labels: enhancement

#256 fix TypeError str / bytes
  core/roslib/src/roslib/network.py
Labels: bug
